version: "3.5"

services:
  php_fpm:
      build: .
      container_name: patterns_php_fpm
      working_dir: /app
      volumes:
          - ./src:/app

  nginx:
      image: nginx:1.15
      container_name: patterns_nginx
      working_dir: /app
      ports:
          - "8080:80"
      volumes:
          - ./src:/app
          - ./docker/nginx/conf.d/default1.conf:/etc/nginx/conf.d/default.conf
